export const SUPABASE_URL = "https://uefphxbvpxtzsfvwcwgz.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlZnBoeGJ2cHh0enNmdndjd2d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc1NTY3MDcsImV4cCI6MjEwMzEzMjcwN30.GzQrsfwSiHbi2_qPZue0GFuu3VUE-5SCdJjIoBxlusU";
